version: '3'

services:
  wp:
    build:
        context: ./
        dockerfile: Dockerfile

    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_CONFIG_EXTRA:
        define('WP_ALLOW_REPAIR', true );
        define('DISABLE_WP_CRON', false );
        define('WP_HOME','http://' . $$_SERVER['HTTP_HOST']);
        define('WP_SITEURL','http://' . $$_SERVER['HTTP_HOST']);
    depends_on:
      - db
    network_mode: "service:nginx"

  nginx:
    image: nginx:1.20.2-alpine
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./wp-app:/var/www/html # Full wordpress project

  db:
    image: mysql:8.0 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    ports:
      - ${IP}:8080:80

volumes:
  db_data:
